* 十二步骤疗法
  
2. 我们承认自己无力控制他人；我们已经无法管理自己的生活。
（或我们承认自己已无力控制自己的上瘾症：性、爱情或其他瘾症；我们已经无法管理自己的生活）
承认自己已经无能为力，再也没有其他任何办法来控制他人；或是已经无力控制自己的上瘾症，我们的生活已经是一团糟，我已无法管理自己的生活。
这是迈向疗愈的第一步，也是最重要的一步。很诚实的看到，自己是如何不爱自己的，以各种方式来残害自己。而且，终于感觉到自我的伤害已经到了自己都忍无可忍的地步，于是愿意将伤害自己的手放下，告诉自己够了，不要再伤害自己了，是谦卑的时候了。这种谦卑是非常好的，对自己非常有益，因为以前骄傲的以为自己无所不能，事实上，是潜意识里的小我无所不能，是小我的自我伤害。
同时，这也是臣服的时候了。所谓臣服是将小我臣服出去、交出去、然后开始问自己，生命一定要这么痛苦吗？生命有没有另一种过法？

2. 我们相信有一个比自己还大的力量，可以恢复我们健全的精神。
相信除了小我与自己之外，有一个比自己还大的力量，可以帮助自己，从这迷宫中走处来，从痛苦中走出来，恢复健全快乐的精神。而这个更大的力量，可以是上帝、菩萨、观音、心灵的导师、内在的神圣，依照每个人的感觉、文化及信仰而定。无论是什么，我们都要相信这个高层力量会带我们走出困境，迈向康庄大道。

3. 我们决定把意志和生命交付给我们所了解的神手上。
我们决定将自己的意志、生命交付给自己所了解的神手上，并且相信这个神是非常爱我们的，只希望最好的事情发生在我们的生命中。神早已为我们准备好所有真善美的礼物，只等着我们开口。当我们觉得困扰、不晓得该怎么办时；当我们生气、难过、嫉妒、惊慌、害怕、无助时；当我们终于决定放下自己脑袋中的喋喋不休、义正词严的找借口时，心里深深的知道这些我们都试过，而且已经做了很多很多次了，每一次都失败，我们终于愿意放下自己的小我，臣服并开口，要求神的帮助，要求神的指引。“我将重担卸给主”静静的等待指示，意即我决定将所有的意志及全部的生命交到神的手上。

4. 对自己做一次内在的追寻和无惧的道德盘点。
这个步骤，很多人选择将过去的历史写下来，若是性上瘾者或爱情上瘾者，可以从自己的性或爱情史来开始写起，看到自己是如何用用样的行为，不断的重复伤人伤己。
诚实的看到自己，由于小我的投射，我们对他人的批评、伤害、控制；我们对旁人的说谎、偷窃行为；我们当受害者的心态及行为；我们以爱、付出、牺牲为名，行控制、掠夺之实，我们以保卫自己为名，行攻击之实......
一次次的深入自己，勇敢的面对自己，做无惧的道德盘点。

5. 对神、对自己和其他人承认我们错误的本质。
做了道德盘点之后，我们对神、对自己及其他人，勇敢的承认自己错误的本质。我们可以选择在支援团体里，分享自己的发现；或是找到一个已经在康复中且了解我们的人（要有爱心及耐心），诚实的对他说出自己所有的过错。而这个团体或个人，不会让我们觉得羞耻，他们只是倾听者，给予我们无限的支持及安慰，让我们了解到所有的过错，事实上都是因为内在受伤的小孩已经伤了自己，伤到了太痛的地步了，所以我们才会做出这样的行为。承认自己错误的本质，是为了得到自己的原谅。
当我们可以承认自己的错误的时候，就是将内在罪恶感释放出来的时候。罪恶感释放出来之后，我们就不会不断无意识的伤害自己。

6. 完全作好准备，让神去除所有品质上的缺失。
当我们终于看到自己品格上的缺失，就要完全做好准备，将自己所有的缺点交给神，让神去除所有品格上的缺失。这是只有神才能做得到的事，我们自己是做不到的。因为所有品格上的缺失都来自小我的妄作，当我们将所有的缺失交出去时，也是我们臣服的时候，相信神会帮助我们，将自己所有的缺点带走。我们唯一需要做的是，就是不断的交出去，不断的祈祷。

7. 谦卑的精神去除我们的缺点。
谦卑是康复行为中最重要的一种特质。我们不再骄傲的认为自己可以做到，这是小我的骄傲，小我认为自己做得到，但小我所知道的就只是不断的伤害自己。我们知道从现在起，生命中有一个神一直与我们同在，而我们唯一需要做的，就是谦卑的臣服，请神去除我们的缺点。

8. 列出曾经被我们伤害过的所有人的名单，并且弥补他们。
列出一个曾经被我们伤害过的名单，并且做好准备弥补他们。名单里不要忘了将自己的名字放上去，这样做并不是让自己有更深的罪恶感，而是释放罪恶感，让自己不再被自己的罪恶感伤害。

9. 一有机会就以直接的方式弥补他们，除非这样的行为会造成他们或别人的伤害。
一有机会，我们就以直接的方式弥补名单上的人，可能是道歉或其他适当的弥补方式。进行弥补行为时，要很谨慎，要了解某些行为可能会造成对方的伤害。记住弥补不只是为了自己，也为了对方，所以一定要考虑对方的状况，对方是否可以接受，或是我们与对方再度联络，是否会伤害到对方。若时机还未到，也许我们可以先写一封信，但不必真的寄出。因为所有人的思想其实都是相连的，我们的爱与歉意对方会收到。心中不断的给对方祝福与诚恳的道歉，时机到的时候，我们会知道。

10. 继续进行道德盘点，发现错误时立刻承认。
继续进行道德盘点，当发现自己有错误时，勇敢且诚实的立刻承认。若发现错误的当下，时机恰当就马上道歉，这样就不会在心里继续累积罪恶感。任何罪恶感的累积，只是在自己的生命中形成更多的障碍，让生活窒息难行。

11. 透过祈祷和静心，改善我们与神的有意识接触；只祈求知识，让我们了解神对我们的旨意；祈求力量，让我们以行动来贯彻。
透过祈祷和静心，让喋喋不休的小我安静下来，我们会开始有能力与神有意识的接触。不断的祈求知识，了解神对我们的旨意；祈求力量，让神来带领我们，以行动来贯彻神对我们的安排。有时候我会每隔半小时就在心里向神祷告，例如在写这本书时，我就不断的祷告，要求神的指引，让我将神的旨意传达出去。此外，我除了常利用呼吸让自己的情绪释放，获得宁静，进而找到答案之外；另一个办法，就是在睡觉前向神祷告，要求在梦里给我答案，并给我宁静与力量。

12. 完成十二步骤，获得心灵的觉醒后，我们会努力把这讯息传递给其他相互依赖者（或其他上瘾者），并且在所有事物中练习这些原则。
在完成这十二步骤，获得心灵的疗愈、觉醒之后，我们要努力将这讯息传递给其他还在上瘾中痛苦的人，并且在生活中不断的练习这些原则、不断的与神有意识的接触、不断的做道德盘点、不断的臣服、不断的原谅自己及他人，学习照顾自己、关怀自己、爱自己、并爱他人。当我们将讯息传递给其他上瘾者时，必须了解这并不是宗教，也不是要拯救任何人。我们量力而为，身教胜于言教，只是让自己发光发亮；而当我们有勇气爱自己时，也给了身旁的人希望，让对方也有勇气开始爱自己，走出自己的困境，踏上康复之路。
