# title: lisp 使用简单教程
献给我的妈妈，如果没有
那么，我，就出不来。


大家好，同学们好，我要写一篇关于 lisp 用法的文章。

基本的 lisp 的使用包含两个过程。

1. 写 lisp 结构的说明文字
2. 用 emacs LISPFILE 的句式执行。

   
** 前言
当你想着扩展 emacs 的功能的时候，那一定是 emacs 的强大的功能满足不了你的时候。
有些人觉得挺愚蠢的，为了在 emacs 上工作，花费大量时间学习扩展。 但如果你把 emacs 当成一个
操作系统学习，那么，花费大量的时间进行扩展学习就不觉得浪费时间了。

木工或者水管工，他们的工具差不多一样，但大小不同，为的就是处理某些事情的时候，工具用的更方便罢了。
emacs 用户，为了使他们使用的工具更加强大，就用不停的增加它的内容。由一个 emacs 初始没什么功能的版本，扩展
到现在这么强大的版本。

在这篇文章里，我会描述我使用 emacs 时的方法。

光标，用来标记文字的位置。在光标处可以进行光标下文字的处理。

emacs 的概念，emacs 是世界上最强大的文本编辑器。emacs 不光是一个文本编辑器，还是一个 代码编辑器。但下面的孩子，你们只是初学者啊，
我要教导的只是编辑器，不管是文本还是代码，应有的功能，从简单的开始。

现在说明下基本的功能的使用。

文字的输入与修改，与光标的关系。

** 定义函数

*** 可选参数
#+begin_src lisp
(defun other-window-back(&optional n)
  "回到上n个窗口"
  (interactive "p")
  (if n
      (other-window (- n))
    (other-window -1)
    )
  )
#+end_src
    
** 辅助帮助
帮助文档，是关于 软件功能 使用的说明，一个软件用途是什么，怎么用解决什么问题，需要有说明文档
   
   - 快捷键的绑定帮助  description-key
   - 功能帮助  description-function
   - 名词描述帮助 description-variable
** 文本编辑器的功能
对 *文本面*  的操作
   
*** 光标
   光标用来指定位置，在地图上，二位坐标系内，我们用坐标点来标记商店的位置（在什么路什么路） 
   三位坐标中，空间中，也可以用点标记位置。
   在文本文件中，也可以用行列坐标标记位置。
   在 CSS 中，用元素的绝对大小来排列元素。也可以用定位光标(left ,right) 来定位元素。
   
*** 添加文字
    insert-char
*** 删去文字
    delete-char
    
*** 滚动
**** 逐行滚动
     scroll-up     


**** 逐列滚动
     scroll-down  默认滚屏一页,加上参数为滚动 n 行
*** 多 Buffer 操作
    多文件编辑
*** 多窗口操作
- 窗口编号
- 窗口定位 

**** 回到上一个窗口  
     #+begin_src lisp
       (defun other-window-back()
         "回到上一个窗口"
         (interactive)

         (other-window -1)
         )
     #+end_src

**** 回到上 n 个窗口
#+begin_src lisp
(defun other-window-back(n)
"回到上n个窗口"
(interactive "p")

(other-window (- n))
)
#+end_src

**** 最好的方式
#+BEGIN_SRC emacs-lisp
  (defun other-window-backward (&optional n)
    "Select Nth previous window."
    (interactive "P")
    (other-window (- (prefix-numeric-value n))))
#+END_SRC

- 大写的 P 表示 "当以交互的方式调用时，将前置参数保持为原始形式并将其赋值给 n"
- prefix-numeric-value 可以将 n 转换成数字，如果 n 为 nil 则返回 1

